"""add_audit_columns_to_all_tables

Revision ID: 7fd8b65372f7
Revises: 8a68f8ad84e6
Create Date: 2026-01-01 21:07:29.802508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd8b65372f7'
down_revision: Union[str, None] = '8a68f8ad84e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager_schedules', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('manager_schedules', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('manager_schedules', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('manager_schedules', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('managers', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('managers', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('managers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('managers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('payments', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('payments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('promotions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('promotions', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('promotions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('reservations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('reservations', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('reservations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('reservations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('user_profiles', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('user_profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('user_profiles', 'is_deleted')
    op.drop_column('user_profiles', 'is_active')
    op.drop_column('user_profiles', 'updated_by')
    op.drop_column('user_profiles', 'created_by')
    op.drop_column('reviews', 'is_deleted')
    op.drop_column('reviews', 'is_active')
    op.drop_column('reviews', 'updated_by')
    op.drop_column('reviews', 'created_by')
    op.drop_column('reservations', 'is_deleted')
    op.drop_column('reservations', 'is_active')
    op.drop_column('reservations', 'updated_by')
    op.drop_column('reservations', 'created_by')
    op.drop_column('promotions', 'is_deleted')
    op.drop_column('promotions', 'updated_by')
    op.drop_column('promotions', 'created_by')
    op.drop_column('payments', 'is_deleted')
    op.drop_column('payments', 'is_active')
    op.drop_column('payments', 'updated_by')
    op.drop_column('payments', 'created_by')
    op.drop_column('managers', 'is_deleted')
    op.drop_column('managers', 'is_active')
    op.drop_column('managers', 'updated_by')
    op.drop_column('managers', 'created_by')
    op.drop_column('manager_schedules', 'is_deleted')
    op.drop_column('manager_schedules', 'is_active')
    op.drop_column('manager_schedules', 'updated_by')
    op.drop_column('manager_schedules', 'created_by')
    # ### end Alembic commands ###
