"""Add feature_key to menus table

Revision ID: d33a6c5f2c1a
Revises: f72dc939c68d
Create Date: 2026-01-09 10:46:28.781787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33a6c5f2c1a'
down_revision: Union[str, None] = 'f72dc939c68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('feature_key', sa.String(length=100), nullable=True, comment='연결된 기능 키 (예: feature.auth.login). 해당 기능이 비활성화되면 메뉴도 숨김'))
    op.create_index(op.f('ix_menus_feature_key'), 'menus', ['feature_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_feature_key'), table_name='menus')
    op.drop_column('menus', 'feature_key')
    # ### end Alembic commands ###
