"""add_menus_table

Revision ID: f72dc939c68d
Revises: a6fe78c613fb
Create Date: 2026-01-09 10:20:06.864169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72dc939c68d'
down_revision: Union[str, None] = 'a6fe78c613fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create user_groups table if not exists
    op.execute("""
    CREATE TABLE IF NOT EXISTS user_groups (
        id UUID PRIMARY KEY,
        name VARCHAR(50) UNIQUE NOT NULL,
        description TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        created_by UUID,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        updated_by UUID,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE
    )
    """)

    # Add group_id column to users table if not exists
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name='users' AND column_name='group_id'
        ) THEN
            ALTER TABLE users ADD COLUMN group_id UUID;
            ALTER TABLE users ADD CONSTRAINT users_group_id_fkey
                FOREIGN KEY (group_id) REFERENCES user_groups(id) ON DELETE SET NULL;
        END IF;
    END $$;
    """)

    # Create menus table
    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('menu_name', sa.String(length=100), nullable=False),
    sa.Column('menu_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('link_url', sa.String(length=1000), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('permission_type', sa.String(length=20), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_expandable', sa.Boolean(), nullable=False),
    sa.Column('default_expanded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_menu_code'), 'menus', ['menu_code'], unique=True)
    op.create_index(op.f('ix_menus_menu_type'), 'menus', ['menu_type'], unique=False)
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_menu_type'), table_name='menus')
    op.drop_index(op.f('ix_menus_menu_code'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
